/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:15ca3f60-8ebd-48d3-a95d-b6575a55a103",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_3UzMwpKDq",
    "aws_user_pools_web_client_id": "3h8ik71l2ckt1auukn65eim134",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://evtirbqpcnh5rcxwujvwsz5mhm.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wl6f7vkekfh3rcy2qxp5ahappe"
};


export default awsmobile;
